// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq7Yf2A7aidyNnoCnJjPKWLGLvum6D71Q',
    appId: '1:669637841837:web:34129e984eea8f48d6c724',
    messagingSenderId: '669637841837',
    projectId: 'fitlink-as-bd',
    authDomain: 'fitlink-as-bd.firebaseapp.com',
    storageBucket: 'fitlink-as-bd.appspot.com',
    measurementId: 'G-S3RQP85CDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQf_2aMfKZhcLR15JzATip6ahhBiRGeII',
    appId: '1:669637841837:android:9e8d6f560d0299aed6c724',
    messagingSenderId: '669637841837',
    projectId: 'fitlink-as-bd',
    storageBucket: 'fitlink-as-bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAblSCv0hfuDe2ZSQO5T3XPrEJi05PZ0uE',
    appId: '1:669637841837:ios:3e383db6a17cc06ed6c724',
    messagingSenderId: '669637841837',
    projectId: 'fitlink-as-bd',
    storageBucket: 'fitlink-as-bd.appspot.com',
    iosClientId: '669637841837-fgdk5pneujte0dr4omto5cof8k036agc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitlink',
  );
}
